travis:
  secure:
    BINSTAR_TOKEN: hl9zVFtEkjsfsugCdewE8dNdCWBlpInHfahoOolmc3fI3PVT9efZvlaxEYfmWauAd1WWxReJlFLyHCSUaiyU+o8D+TBxQG0MQXZgJ8ViT655g3xS5934L5OX4wQFqlPIDVXtGLj390RLPb+qApJYbRPOfR05weZwcgR+A9OsXS5Bw6n9f6SvKtuDk0eFa1ledJuSQpjWQTmZUj7NsBGsNnQy813zQMt2e2TfsWHu4a7YgUDofqTBAunR2TmC5l/DrlRy084xaVvafY1vHflbdKZvLIcQmBNL0MzPvTjYovFwvHKrywizR0oP2PRpuCmynk+R770bkaQYKnMRJyyqEktRZRPKlptPsTJ8FiEVQpFXWguPZdZjaQBMJSj6JUA36m/m1M0Tyyd95s28B/tffiCYPSOohgHOMHYgDjO4GpgqBl8nwPIXMpwsaB8gAnzlhiXvy2biL2U7GlUpBae5EqwdYyxFPnJDp8AsFUmRLiyjMC2k5C+dbyQ2yF3DucahlVe70AE1KpC/HmL+VFRADhnNMx1QYmZE3V6q5q7rwJL2gsvK24GtnvbhPmMVWAQmLtakf19zUdadLdxyKbOBzBjLFmgs5qQ2MHJEYlR2QV2EfFwaJm8sM2EpP8oEEN4fa9a6ElfDr1odZtKQiyvJ5VOJxITmxsOHBubFLGo4SEI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
